## Setup

In [ ]:
# !pip install -U scikit-learn

In [ ]:
from sklearn.linear_model import LinearRegression

## Load DataSets
Ready to use

In [1]:
from sklearn.datasets import load_iris

In [2]:
Iris = load_iris()
Iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
print(Iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [4]:
print(Iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
import pandas as pd

In [10]:
Iris_Data = pd.DataFrame(Iris['data'])   # or Iris.Data
Iris_Data.head(10)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
5  5.4  3.9  1.7  0.4
6  4.6  3.4  1.4  0.3
7  5.0  3.4  1.5  0.2
8  4.4  2.9  1.4  0.2
9  4.9  3.1  1.5  0.1

In [11]:
Iris_Data.shape

(150, 4)

In [12]:
print(Iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
print(Iris.target_names)

['setosa' 'versicolor' 'virginica']


## Generate Dataset

In [14]:
from sklearn.datasets import make_regression

In [15]:
x, y = make_regression(n_samples = 30, n_features = 3, shuffle = True)
x.shape

(30, 3)

In [16]:
x

array([[ 0.67915508, -1.53119031, -0.64125162],
       [-0.23064518,  0.89792953, -0.48716324],
       [-0.57211686,  0.7808067 , -1.54865178],
       [ 0.04867081,  0.58696046, -0.74230451],
       [-0.32699527,  0.43227596,  0.70456149],
       [-0.16540611, -0.16007131, -2.54776395],
       [ 1.32993224,  0.3856454 , -0.30382316],
       [-0.82643229, -1.19918609, -1.45329644],
       [ 1.08079041,  0.12642007, -0.24904011],
       [ 0.45749894, -0.45523326,  0.07926993],
       [-1.49446832, -0.29921824, -0.28027062],
       [-1.0715471 , -0.53970689,  0.22395372],
       [ 0.17126393, -2.32063116, -0.8187451 ],
       [ 1.29165604, -0.54939018,  0.18145304],
       [-0.62202688,  0.84684241,  0.48107104],
       [ 2.15771118,  0.75412828, -0.05534774],
       [-0.65469518, -1.53982083, -0.57891212],
       [ 0.89625216,  0.59274825,  0.47611605],
       [ 0.62787704,  1.18698035, -0.69936547],
       [-1.85591972,  0.86045907,  0.23056393],
       [-1.23196113, -1.0982859 , -0.864

In [17]:
y  # target

array([ -78.36725055,    7.89712566, -101.61903492,   -1.83666524,
         41.85409916, -189.23744262,  139.99562509, -257.29683735,
        100.7579934 ,   19.33877188, -187.53660246, -129.88838757,
       -194.6825458 ,  102.58610605,   26.77475747,  263.75090648,
       -208.11815287,  160.48089563,  100.01110467, -111.32521009,
       -253.44398133,    1.75544709, -177.39336767,  -87.27581198,
        -71.16947823,  -40.82270991, -123.52575278,  -92.03939358,
         -1.71517014,  128.2657254 ])

In [18]:
from sklearn.datasets import make_classification

In [20]:
x, y = make_classification(n_samples = 30, n_features = 6, n_classes = 2)

In [21]:
x.shape

(30, 6)

In [22]:
x

array([[ 2.01616019, -1.27560975,  0.77114348, -0.72725126,  0.33961861,
         0.15546002],
       [-1.7926818 ,  0.81068949, -0.77939697, -1.15219249,  0.12981615,
        -0.09970054],
       [-2.23362042, -0.26204884, -0.09778934, -0.57120514,  1.85958794,
         0.02727136],
       [ 0.56380477, -1.13835293, -1.86064237, -1.04437606,  1.13817212,
         0.13655585],
       [-1.03500305, -0.17202513, -1.85629958,  1.63234887,  0.92921614,
         0.01866244],
       [ 1.13085481, -0.9424759 , -1.35677743, -1.90907976,  0.49344217,
         0.11422854],
       [ 1.22324341, -0.88004476, -0.73450098, -0.31756116,  0.34766803,
         0.1069566 ],
       [ 1.55183108,  0.7480803 , -1.8420721 , -0.76779752, -2.04739637,
        -0.08635234],
       [-2.67392417, -0.54895084,  0.64728523, -0.08688131,  2.54012686,
         0.06066181],
       [ 0.95123703, -1.40067783,  0.49885812, -0.51842585,  1.22638924,
         0.16847779],
       [-0.54682093,  0.88195861,  0.11644269, -1.

In [23]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0])

# Data Preparation

## Data Cleaning

In [24]:
import numpy as np
from sklearn.impute import SimpleImputer

In [25]:
imp_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [26]:
data = [[2,      3,       9],
        [2,      None,    9],
        [1,      np.nan,  9],
        [1,      3,       0],
        [np.nan, 8,       2],
        [1,      0,       np.nan]]

imp_mean.fit(data)

SimpleImputer()

In [27]:
imp_mean.transform(data)

array([[2. , 3. , 9. ],
       [2. , 3.5, 9. ],
       [1. , 3.5, 9. ],
       [1. , 3. , 0. ],
       [1.4, 8. , 2. ],
       [1. , 0. , 5.8]])

### Find Missing Data in CSV Files

In [28]:
import pandas as pd

In [29]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example.csv')
data

x1  x2   x3  x4    x5    x6
0  1.0   2  5.0   0   4.0   NaN
1  1.0  15  NaN   1  16.0   2.0
2  NaN   3  1.0   2   3.2   4.0
3  5.0   4  6.0   8   1.0   NaN
4  7.0   3  NaN   6   5.0  15.0
5  2.0   1  6.0   1   1.0   3.0

In [30]:
data.dtypes

x1    float64
x2      int64
x3    float64
x4      int64
x5    float64
x6    float64
dtype: object

In [31]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example2.csv')
data

x1  x2   x3  x4    x5    x6         x7
0  1.0   2  5.0   0   4.0   NaN         10
1  1.0  15  NaN   1  16.0   2.0          ?
2  NaN   3  1.0   2   3.2   4.0          2
3  5.0   4  6.0   8   1.0   NaN          ?
4  7.0   3  NaN   6   5.0  15.0          3
5  2.0   1  6.0   1   1.0   3.0  UNDEFINED

In [32]:
data.dtypes

x1    float64
x2      int64
x3    float64
x4      int64
x5    float64
x6    float64
x7     object
dtype: object

In [33]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example2.csv', na_values = ['?', "UNDEFINED"])
data

x1  x2   x3  x4    x5    x6    x7
0  1.0   2  5.0   0   4.0   NaN  10.0
1  1.0  15  NaN   1  16.0   2.0   NaN
2  NaN   3  1.0   2   3.2   4.0   2.0
3  5.0   4  6.0   8   1.0   NaN   NaN
4  7.0   3  NaN   6   5.0  15.0   3.0
5  2.0   1  6.0   1   1.0   3.0   NaN

In [34]:
data.dtypes

x1    float64
x2      int64
x3    float64
x4      int64
x5    float64
x6    float64
x7    float64
dtype: object

In [35]:
mask = data.isnull()
mask

x1     x2     x3     x4     x5     x6     x7
0  False  False  False  False  False   True  False
1  False  False   True  False  False  False   True
2   True  False  False  False  False  False  False
3  False  False  False  False  False   True   True
4  False  False   True  False  False  False  False
5  False  False  False  False  False  False   True

In [36]:
mask.any(axis = 1)


0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool

In [37]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example3.csv')
data

x1  x2    x3    x4  x5  x6
0  10.0   1   4.0   7.0   3   2
1  20.0  12   NaN  12.0   4   5
2   NaN   5  15.0  12.0   3   6
3  40.0   1   6.0   NaN  44   0
4  50.0   2  12.0  12.0   3   1
5  60.0   4   6.0  17.0   5   4

In [38]:
mask = data.isnull().any(axis = 1)
mask

0    False
1     True
2     True
3     True
4    False
5    False
dtype: bool

In [41]:
new_data = data[~mask]
new_data

x1  x2    x3    x4  x5  x6
0  10.0   1   4.0   7.0   3   2
4  50.0   2  12.0  12.0   3   1
5  60.0   4   6.0  17.0   5   4

### Remove Rows/Columns with missing values

In [42]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example4.csv')
data.head(10)

x1  x2  x3    x4  x5  x6
0   10.0   1   4   7.0   3   2
1   20.0  12   5  12.0   4   5
2    NaN   5  15  12.0   3   6
3   40.0   1   6   3.0  44   0
4   50.0   2  12   7.0   3   1
5   60.0   4   6  17.0   5   4
6   70.0   5   4   7.0   3   2
7   80.0  21   5  12.0   4   5
8   90.0   5  15  12.0   3   6
9  100.0  17   6   NaN  44   0

In [43]:
data.isnull().any(axis = 1).sum()

2

#### 1. Using Mask

In [44]:
mask = data.isnull().any(axis = 1)
new_data = data[~mask]
new_data.head(10)

x1  x2  x3    x4  x5  x6
0    10.0   1   4   7.0   3   2
1    20.0  12   5  12.0   4   5
3    40.0   1   6   3.0  44   0
4    50.0   2  12   7.0   3   1
5    60.0   4   6  17.0   5   4
6    70.0   5   4   7.0   3   2
7    80.0  21   5  12.0   4   5
8    90.0   5  15  12.0   3   6
10  110.0   2  14  20.0   3   1
11  120.0   4   6  17.0   5   4

#### 2. Using Drop Function

In [45]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example4.csv')

new_data = data.dropna()

new_data.head(10)

x1  x2  x3    x4  x5  x6
0    10.0   1   4   7.0   3   2
1    20.0  12   5  12.0   4   5
3    40.0   1   6   3.0  44   0
4    50.0   2  12   7.0   3   1
5    60.0   4   6  17.0   5   4
6    70.0   5   4   7.0   3   2
7    80.0  21   5  12.0   4   5
8    90.0   5  15  12.0   3   6
10  110.0   2  14  20.0   3   1
11  120.0   4   6  17.0   5   4

### Replace missing value (Imputation)

In [46]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example5.csv')
data.head(10)

x1  x2    x3    x4  x5  x6
0   10.0   1   NaN   7.0   3   2
1   20.0  12   5.0  12.0   4   5
2    NaN   5   NaN  12.0   3   6
3   40.0   1   NaN   3.0  44   0
4   50.0   2  12.0   7.0   3   1
5   60.0   4   NaN  17.0   5   4
6   70.0   5   4.0   7.0   3   2
7   80.0  21   NaN  12.0   4   5
8   90.0   5   NaN  12.0   3   6
9  100.0  17   NaN   NaN  44   0

In [47]:
new_data = data.fillna(data.mean())
new_data.head(10)

x1  x2         x3         x4  x5  x6
0   10.000   1   8.266667   7.000000   3   2
1   20.000  12   5.000000  12.000000   4   5
2  140.625   5   8.266667  12.000000   3   6
3   40.000   1   8.266667   3.000000  44   0
4   50.000   2  12.000000   7.000000   3   1
5   60.000   4   8.266667  17.000000   5   4
6   70.000   5   4.000000   7.000000   3   2
7   80.000  21   8.266667  12.000000   4   5
8   90.000   5   8.266667  12.000000   3   6
9  100.000  17   8.266667  10.774194  44   0

In [50]:
new_data = data.fillna({'x1' : 0.0, 'x3' : data['x3'].mean(), 'x4' : data['x4'].median()})
new_data.head(10)

x1  x2         x3    x4  x5  x6
0   10.0   1   8.266667   7.0   3   2
1   20.0  12   5.000000  12.0   4   5
2    0.0   5   8.266667  12.0   3   6
3   40.0   1   8.266667   3.0  44   0
4   50.0   2  12.000000   7.0   3   1
5   60.0   4   8.266667  17.0   5   4
6   70.0   5   4.000000   7.0   3   2
7   80.0  21   8.266667  12.0   4   5
8   90.0   5   8.266667  12.0   3   6
9  100.0  17   8.266667  12.0  44   0

In [52]:
imp = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imp.fit(data)
new_data = pd.DataFrame(imp.transform(data))
new_data.head()

0     1          2     3     4    5
0   10.000   1.0   8.266667   7.0   3.0  2.0
1   20.000  12.0   5.000000  12.0   4.0  5.0
2  140.625   5.0   8.266667  12.0   3.0  6.0
3   40.000   1.0   8.266667   3.0  44.0  0.0
4   50.000   2.0  12.000000   7.0   3.0  1.0

In [ ]:
new_data = imp.fit_transform(data)
new_data

In [53]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example6.csv')
data

x1  x2    x3  x4  x5  x6
0  10   1   low   7   3   2
1  20  12   NaN  12   4   5
2  30   5  high  12   3   6
3  40   1  high   3  44   0
4  50   2   NaN   7   3   1
5  60   4   low  17   5   4
6  70   5   med   7   3   2
7  80  21  high  12   4   5
8  90   5  high  12   3   6

In [54]:
data['x3'].value_counts()

x3
high    4
low     2
med     1
Name: count, dtype: int64

In [55]:
data['x3'].mode()

0    high
Name: x3, dtype: object

In [56]:
new_data = data.fillna({'x3' : data['x3'].mode()[0]})
new_data

x1  x2    x3  x4  x5  x6
0  10   1   low   7   3   2
1  20  12  high  12   4   5
2  30   5  high  12   3   6
3  40   1  high   3  44   0
4  50   2  high   7   3   1
5  60   4   low  17   5   4
6  70   5   med   7   3   2
7  80  21  high  12   4   5
8  90   5  high  12   3   6

more about replacing [check this](https://www.programiz.com/python-programming/pandas/handle-missing-values)
---
----

## Data Encoding
- **Binary Data** : Only two possible value
    - Gender (male/female), yes/no, etc.
- **Nominal Data** (Categorical) Order is not Important
    - Country : Egypt, UK, Morocco, etc.
- **Ordinal Data** : Order is Important
    - Size : xs < s < m < l < xl
    - Level : low < medium < high

#### using LabelEncoder

In [57]:
from sklearn.preprocessing import LabelEncoder

In [58]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example7.csv')
data

x1  x2    x3          x4  x5  x6
0    male   1   low   full-time   3   2
1    male  12   med   part-time   4   5
2  female   5  high   full-time   3   6
3    male   1  high  unemployed  44   0
4  female   2   low   part-time   3   1
5    male   4   low  unemployed   5   4
6    male   5   med   full-time   3   2
7  female  21  high   part-time   4   5
8  female   5  high   full-time   3   6

In [59]:
LE = LabelEncoder()
data['x1'] = LE.fit_transform(data['x1'])
data

x1  x2    x3          x4  x5  x6
0   1   1   low   full-time   3   2
1   1  12   med   part-time   4   5
2   0   5  high   full-time   3   6
3   1   1  high  unemployed  44   0
4   0   2   low   part-time   3   1
5   1   4   low  unemployed   5   4
6   1   5   med   full-time   3   2
7   0  21  high   part-time   4   5
8   0   5  high   full-time   3   6

In [60]:
data['x3'] = LE.fit_transform(data['x3'])
data['x4'] = LE.fit_transform(data['x4'])
data

x1  x2  x3  x4  x5  x6
0   1   1   1   0   3   2
1   1  12   2   1   4   5
2   0   5   0   0   3   6
3   1   1   0   2  44   0
4   0   2   1   1   3   1
5   1   4   1   2   5   4
6   1   5   2   0   3   2
7   0  21   0   1   4   5
8   0   5   0   0   3   6

In [61]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example7.csv')
data

x1  x2    x3          x4  x5  x6
0    male   1   low   full-time   3   2
1    male  12   med   part-time   4   5
2  female   5  high   full-time   3   6
3    male   1  high  unemployed  44   0
4  female   2   low   part-time   3   1
5    male   4   low  unemployed   5   4
6    male   5   med   full-time   3   2
7  female  21  high   part-time   4   5
8  female   5  high   full-time   3   6

In [62]:
print(data['x1'].unique())
print(data['x3'].unique())
print(data['x4'].unique())

['male' 'female']
['low' 'med' 'high']
['full-time' 'part-time' 'unemployed']


In [64]:
new_data =  data.replace({
                'x1' : {'male' : 0, 'female' : 1},                              # binary data
                'x3' : {'low' : 0, 'med' : 1, 'high' : 2},                      # Ordenary data
                # 'x4' : {'full-time' : 0, 'part-time' : 1, 'unemployed' : 2}     # Nominal Data  (One Hot)
            })
new_data

x1  x2  x3          x4  x5  x6
0   0   1   0   full-time   3   2
1   0  12   1   part-time   4   5
2   1   5   2   full-time   3   6
3   0   1   2  unemployed  44   0
4   1   2   0   part-time   3   1
5   0   4   0  unemployed   5   4
6   0   5   1   full-time   3   2
7   1  21   2   part-time   4   5
8   1   5   2   full-time   3   6

#### Using One-Hot

- by get_dummies()

In [65]:
data__encoded_one_hot =  pd.get_dummies(new_data)
data__encoded_one_hot

x1  x2  x3  x5  x6  x4_full-time  x4_part-time  x4_unemployed
0   0   1   0   3   2          True         False          False
1   0  12   1   4   5         False          True          False
2   1   5   2   3   6          True         False          False
3   0   1   2  44   0         False         False           True
4   1   2   0   3   1         False          True          False
5   0   4   0   5   4         False         False           True
6   0   5   1   3   2          True         False          False
7   1  21   2   4   5         False          True          False
8   1   5   2   3   6          True         False          False

In [68]:
# data__encoded_one_hot.replace({True : 1, False : 0})
# data__encoded_one_hot

- by OneHotEncoder()

In [ ]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder()

---

## Data Spliting
- **Training**: A subset of the main dataset will feed into the model so that that model can learn the data patterns.
- **Validation**: This set is used to understand the performance of the model in comparison to different models and hyperparameter choices.
- **Test**: This set checks the final model’s accuracy.

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
print(len(data))
data.head()

128


x1    x2       x3  y
0   2  5300  1000000  0
1   1  2100  2000000  0
2   3  1500  3200000  1
3   5  6700  3521000  0
4   1  3200  5230000  0

In [71]:
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']

data_input.head()

x1    x2       x3
0   2  5300  1000000
1   1  2100  2000000
2   3  1500  3200000
3   5  6700  3521000
4   1  3200  5230000

In [72]:
x_train, x, y_train, y       = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)

x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)

In [73]:
print(len(x_train))
x_train.head()

89


x1    x2       x3
22   5  4545  1010102
44   8  2123  5545689
65   1  2100  2000000
95   2  1123  1235689
30   5  1321  2135893

In [74]:
print(len(x_val))
x_val.head()

20


x1    x2       x3
24   3  9513  1231231
89   5  6894  5165846
98   3  1500  3200000
4    1  3200  5230000
12   8  2123  5545689

In [75]:
print(len(x_test))
x_test.head()

19


x1    x2       x3
27   2  5465  3023232
40   5  2300  6821530
15   3  1518  1235489
10   4  6259  2235489
19   3  6543  1222335

---

## Data Normalization (Scaling)

![](https://miro.medium.com/v2/resize:fit:720/format:webp/1*tNRMMFhNcYdOP7KebtTfSA.png)

### Why ?
1. Important for distance-based algorithms :
    - K-means - Clustering
    - K nearest neighbours (KNN) - Classification
    - Principal Component Analysis (PCA) - Dimensionality reduction
    > Without it the features with large ranges will **dominate**
2. Important for gradient-based algorithms :
    - Linear/Non-linear Regression
    - Logistic Regression
    - Neural Networks
    > Without it training will become **slow and may oscillate**

However some algorithms work fine without feature scalling **because** they *work on each feature independently*:
- Decision Trees
- Naive Bayes Classifier

### When ?
- After Data Spliting the dataset to (training - validation - testing) on taining input **ONLY** - not entire dataset

### How ?

#### Using Standardization

$$\large{X_{new} = \frac{X_{old} - \mu}{σ}}$$
where :
- $\mu$ : mean
- $σ$ : Standard Deviation

In [78]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)
data_input.head()

x1    x2       x3
0   2  5300  1000000
1   1  2100  2000000
2   3  1500  3200000
3   5  6700  3521000
4   1  3200  5230000

In [79]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

x_val_scaled = scaler.fit_transform(x_val)
x_test_scaled = scaler.fit_transform(x_test)

'''
or

x_train_scaled = scaler.fit_transform(x_train)

'''
x_train_scaled[:10]

array([[ 0.70959038, -0.07638644, -0.894476  ],
       [ 1.9984382 , -0.97067862,  0.90446878],
       [-1.00887339, -0.97917107, -0.50185387],
       [-0.57925745, -1.33991569, -0.80500168],
       [ 0.70959038, -1.26680675, -0.44795478],
       [ 0.70959038, -1.26680675, -0.44795478],
       [ 0.70959038,  0.79095144,  0.75381207],
       [ 1.13920632,  0.53470091,  2.51872213],
       [-1.00887339, -0.97917107, -0.50185387],
       [-0.14964151, -1.20071331, -0.02589921]])

In [80]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_train_scaled.head()

x1        x2        x3
0  0.709590 -0.076386 -0.894476
1  1.998438 -0.970679  0.904469
2 -1.008873 -0.979171 -0.501854
3 -0.579257 -1.339916 -0.805002
4  0.709590 -1.266807 -0.447955

#### Using MinMaxScaler() - Normalization
$$\large{X_{new} = \frac{X_{old} - X_{min}}{X_{max} - X_{min}}} $$

- Values wil be between $[0, 1]$

In [81]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)

In [82]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

x_train_scaled = pd.DataFrame(scaler.fit_transform(x_train))

x_train_scaled.head()

0         1         2
0  0.7  0.391830  0.001173
1  1.0  0.115472  0.527610
2  0.3  0.112848  0.116068
3  0.4  0.001369  0.027356
4  0.7  0.023962  0.131841

#### Using Normalizer
by Rows

In [83]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)

x_train.head()

x1    x2       x3
22   5  4545  1010102
44   8  2123  5545689
65   1  2100  2000000
95   2  1123  1235689
30   5  1321  2135893

In [87]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer(norm = 'max')

x_train_scaled = pd.DataFrame(scaler.fit_transform(x_train))

x_train_scaled.head()

0         1    2
0  4.949995e-06  0.004500  1.0
1  1.442562e-06  0.000383  1.0
2  5.000000e-07  0.001050  1.0
3  1.618530e-06  0.000909  1.0
4  2.340941e-06  0.000618  1.0

norm = 'l1'
- Summition of each element in the **ROW** and divide by it

norm = 'l2'
- Summition of **Squares** of each element in the **ROW** and divide the element by the sum

norm = 'max'
- Divide maximum of the row by each element

#### Using MaxAbsScaler()
by Columns

In [88]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)


In [89]:
from sklearn.preprocessing import MaxAbsScaler

MAS = MaxAbsScaler()

x_train_scaled = pd.DataFrame(MAS.fit_transform(x_train))

x_train_scaled.head()

0         1         2
0  0.625  0.460253  0.105048
1  1.000  0.214987  0.576737
2  0.125  0.212658  0.207995
3  0.250  0.113722  0.128508
4  0.625  0.133772  0.222127

#### Using FunctionTransformer()
and Write your function

In [90]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)


In [91]:
from sklearn.preprocessing import FunctionTransformer

In [92]:
def f1(x) :
    return x ** 2

In [93]:
FT = FunctionTransformer(f1)

x_train_scaled = pd.DataFrame(FT.fit_transform(x_train))

x_train_scaled.head()

x1        x2              x3
22  25  20657025   1020306050404
44  64   4507129  30754666484721
65   1   4410000   4000000000000
95   4   1261129   1526927304721
30  25   1745041   4562038907449

#### Using Binarizer()

In [94]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)


In [95]:
from sklearn.preprocessing import Binarizer

In [97]:
B = Binarizer(threshold = 100)

x_train_scaled = pd.DataFrame(B.fit_transform(x_train))

x_train_scaled.head()

0  1  2
0  0  1  1
1  0  1  1
2  0  1  1
3  0  1  1
4  0  1  1

#### Using PolynomialFeatures()

In [98]:
data = pd.read_csv('/content/drive/MyDrive/Data-examples/example8.csv')
data_input  = data.drop('y', axis = 1)   # columns = ['y']
data_output = data['y']
x_train, x, y_train, y = train_test_split(data_input, data_output, test_size = 0.3, random_state = 42)
x_test, x_val, y_test, y_val = train_test_split(x, y, test_size = 0.5, random_state = 42)


In [99]:
from sklearn.preprocessing import PolynomialFeatures

In [101]:
PF = PolynomialFeatures(degree = 2, interaction_only = False)

x_train_scaled = pd.DataFrame(PF.fit_transform(x_train))

x_train_scaled.head()

0    1       2          3     4        5           6           7  \
0  1.0  5.0  4545.0  1010102.0  25.0  22725.0   5050510.0  20657025.0   
1  1.0  8.0  2123.0  5545689.0  64.0  16984.0  44365512.0   4507129.0   
2  1.0  1.0  2100.0  2000000.0   1.0   2100.0   2000000.0   4410000.0   
3  1.0  2.0  1123.0  1235689.0   4.0   2246.0   2471378.0   1261129.0   
4  1.0  5.0  1321.0  2135893.0  25.0   6605.0  10679465.0   1745041.0   

              8             9  
0  4.590914e+09  1.020306e+12  
1  1.177350e+10  3.075467e+13  
2  4.200000e+09  4.000000e+12  
3  1.387679e+09  1.526927e+12  
4  2.821515e+09  4.562039e+12