In [1]:
import numpy as np

## Matrix addition & subtraction
As long as the dimensions of two matrices are the same, we can add and subtract them much like we add and subtract numbers

In [2]:
a = np.random.randint(0, 12, (3, 4))
b = np.random.randint(0, 12, (3, 4))

print(a)
print(b)

[[ 0  7  6  8]
 [11  4 10  1]
 [ 2  6 11  6]]
[[7 8 6 4]
 [6 2 6 1]
 [9 3 7 3]]


In [3]:
sum = a + b
print(sum, end = "\n")

# or

sum = np.add(a, b)
print(sum)

[[ 7 15 12 12]
 [17  6 16  2]
 [11  9 18  9]]
[[ 7 15 12 12]
 [17  6 16  2]
 [11  9 18  9]]


In [4]:
sub = a - b
print(sub, end = "\n\n")

# or

sub = np.subtract(a, b)
print(sub)

[[-7 -1  0  4]
 [ 5  2  4  0]
 [-7  3  4  3]]

[[-7 -1  0  4]
 [ 5  2  4  0]
 [-7  3  4  3]]


In [5]:
a = np.random.randint(0, 12, (3, 4))
b = 12

print(a)
print(b)
print(a + b)

[[ 7  5  7  2]
 [ 3  5  6  6]
 [11  8  7  7]]
12
[[19 17 19 14]
 [15 17 18 18]
 [23 20 19 19]]


In [6]:
a = np.random.randint(0, 12, (3, 4))
b = 12

print(a)
print(b)
print(a - b)

[[10 11 10  4]
 [10  4 10 11]
 [ 5  1  2 11]]
12
[[ -2  -1  -2  -8]
 [ -2  -8  -2  -1]
 [ -7 -11 -10  -1]]


In [7]:
a = np.random.randint(0, 12, (3, 4))
b = np.random.randint(0, 12, (3, 4))
print(a, end = "\n\n")
print(b, end = "\n\n")

c = a * b                           # Multiply each element by its corresponding element only
print(c, end = "\n\n")

# or

c = np.multiply(a, b)
print(c)

[[ 4  4  8  2]
 [ 0  6  6  1]
 [10 11  9 11]]

[[ 3  0 11  6]
 [ 3  2  3  0]
 [11  5  9  9]]

[[ 12   0  88  12]
 [  0  12  18   0]
 [110  55  81  99]]

[[ 12   0  88  12]
 [  0  12  18   0]
 [110  55  81  99]]


In [8]:
a = np.random.randint(0, 12, (3, 4))
b = np.random.randint(0, 12, (3, 4))

print(a, end = "\n\n")
print(b, end = "\n\n")

c = a / b
print(c, end = "\n\n")

# or

d = np.divide(a, b)

print(d)

[[ 2  4  2 11]
 [ 6  1 11 10]
 [ 3  3  5  4]]

[[ 6  0  7 11]
 [ 3  4  8  4]
 [11  1  5  7]]

[[0.33333333        inf 0.28571429 1.        ]
 [2.         0.25       1.375      2.5       ]
 [0.27272727 3.         1.         0.57142857]]

[[0.33333333        inf 0.28571429 1.        ]
 [2.         0.25       1.375      2.5       ]
 [0.27272727 3.         1.         0.57142857]]


C:\Users\mazen\AppData\Local\Temp\ipykernel_3772\2703180343.py:7: RuntimeWarning: divide by zero encountered in divide
  c = a / b
C:\Users\mazen\AppData\Local\Temp\ipykernel_3772\2703180343.py:12: RuntimeWarning: divide by zero encountered in divide
  d = np.divide(a, b)


## Maltiply Matrices
when Maltiply a matrix by another matrix we need to do the [dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of rows and columns see [Math is FUN](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
<p align="center">
  <img src="multiply.svg"/>
</p>

In [9]:
a = np.random.randint(0, 12, (3, 4))
b = np.random.randint(0, 12, (4, 3))

print(a)
print(b, end = "\n\n")

c = a @ b

# or

d = np.dot(a, b)

print(c, end = "\n\n")
print(d)

[[3 8 9 2]
 [1 6 1 1]
 [2 5 2 2]]
[[ 3  9  6]
 [11  1  0]
 [ 4  9  1]
 [ 3 11  8]]

[[139 138  43]
 [ 76  35  15]
 [ 75  63  30]]

[[139 138  43]
 [ 76  35  15]
 [ 75  63  30]]


In [10]:
a = np.random.randint(0, 12, (3, 4))
b = np.sum(a)                      # sum of all elements using numpy
c = a.sum()                        # sum of all elements
d = np.sum(a, axis = None)         # sum of all elements
e = a.sum(axis = 0)                # sum of each column
f = np.sum(a, axis = 0)            # sum of each column
g = a.sum(axis = 1)                # sum of each row
h = np.sum(a, axis = 1)            # sum of each row

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[[ 8 11 10 11]
 [10 11  3  8]
 [ 0 11 11  4]]
98
98
98
[18 33 24 23]
[18 33 24 23]
[40 32 26]
[40 32 26]


In [11]:
b = np.sort(a, axis = 0)        # sort each column
c = np.sort(a, axis = 1)        # sort each row

print(b, end = "\n\n")
print(c)

[[ 0 11  3  4]
 [ 8 11 10  8]
 [10 11 11 11]]

[[ 8 10 11 11]
 [ 3  8 10 11]
 [ 0  4 11 11]]


In [12]:
a = np.random.randint(0, 12, (3, 3))
b = np.linalg.inv(a)              # inverse of a matrix

c = np.dot(a, b)


print(a)

print(b)

print(c)

[[1 6 7]
 [8 3 0]
 [2 0 5]]
[[-0.05617978  0.11235955  0.07865169]
 [ 0.14981273  0.03370787 -0.20973783]
 [ 0.02247191 -0.04494382  0.16853933]]
[[ 1.00000000e+00  0.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [13]:
a = np.array([0, 20, 40, 60, 80, 10, 120, 140, 160, 180])
b = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

x, y = np.polynomial.Polynomial.fit(a, b, 1, full = True)

print(x)
# print(y)

i, j = np.polyfit(a, b, 1)

print(i)
# print(j)

5.12470772 - 3.75292284 x
-0.04169914263445055


In [14]:
a = np.poly1d(5)
b = np.poly1d((4, 8))
c = np.poly1d((77, 8, 2))
d = np.poly1d([7, 5, 2, 15])

print(a)
print(b)
print(c)
print(d)

 
5
 
4 x + 8
    2
77 x + 8 x + 2
   3     2
7 x + 5 x + 2 x + 15


In [15]:
a = np.poly1d([7, 5, 2, 15])
b = a(1)
c = a(4)
d = a(0)

print(a)
print(b)
print(c)
print(d)

   3     2
7 x + 5 x + 2 x + 15
29
551
15


In [16]:
a = np.polyval([7, 5, 2, 15], 2)
b = np.polyval([7, 5, 2, 15], 0)

print(a)
print(b)

95
15


In [17]:
a = np.poly1d([2, 3, 4, 5])
b = np.roots(a)
# or
c = a.roots


print(a)
print(b)
print(c)

   3     2
2 x + 3 x + 4 x + 5
[-1.37113433+0.j         -0.06443283+1.34876101j -0.06443283-1.34876101j]
[-1.37113433+0.j         -0.06443283+1.34876101j -0.06443283-1.34876101j]


In [18]:
a = np.array('2015-07-31', dtype = np.datetime64)
b = np.datetime64('2015-12-31')

print(a)
print(b)

2015-07-31
2015-12-31


In [19]:
print(a + 1)

print(b + 1)

2015-08-01
2016-01-01


In [20]:
a = np.datetime64('2015-07-04')
listofDates_1 = np.arange(a, np.datetime64('2015-07-10'))
print(listofDates_1, end = "\n\n")
# or
listofDates_2 = np.arange(np.datetime64('2015-07-04'), np.datetime64('2015-07-10'))
print(listofDates_2, end = "\n\n")
# or
listofDates_3 = a + np.arange(6)
print(listofDates_3)

['2015-07-04' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-07-09']

['2015-07-04' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-07-09']

['2015-07-04' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-07-09']
