## Linear Algebra
- [Numpy](https://numpy.org/doc/stable/reference/routines.linalg.html)
- [Scipy](https://docs.scipy.org/doc/scipy/reference/linalg.html#eigenvalue-problems) 

In [1]:
import numpy as np

### Dot product of two arrays or more

In [2]:
np.dot(4, 5)

20

In [3]:
A = [[1, 0], [0, 1]]
B = [[4, 1], [2, 2]]
np.dot(A, B)

array([[4, 1],
       [2, 2]])

In [4]:
A = [[1, 0], [0, 1]]
B = [[4, 1], [2, 2]]
C = [[1, 0], [0, 1]]
D = [[4, 1], [2, 2]]

# instead of 
# _ = np.dot(np.dot(np.dot(A, B), C), D)
# or
# _ = A.dot(B).dot(C).dot(D)
# you can use 

np.linalg.multi_dot([A, B, C, D])

array([[18,  6],
       [12,  6]])

### Dot product of two vectors

In [5]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])

# 1*4 + 4*1 + 5*2 + 6*2

r1 = np.vdot(a, b)
r2 = np.vdot(b, a)

print(r1, r2)

30 30


### Square matrix to the (integer) power n

In [6]:
a = np.array([[0, 1], [-1, 0]])

np.linalg.matrix_power(a, 3)

array([[ 0, -1],
       [ 1,  0]])

### Cross product of 3-element vectors

In [7]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

### Eigenvalues and Eigenvectors

In [8]:
Mat = np.array([[1, 4],
                [2, 3]])

print(np.linalg.eigvals(Mat))

[-1.  5.]


In [9]:
Mat = np.array([[1, 4], 
                [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(Mat)

print(eigenvalues)
print(eigenvectors)

[-1.  5.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Determinant of an array

In [10]:
a = np.array([[1, 2], 
              [3, 4]])

np.linalg.det(a)

-2.0000000000000004

### Sum of diagonal elements

In [11]:
a = np.array([[1, 2],
              [3, 4]])

np.trace(a)
# or
np.sum(np.diag(a))

5

### Solve linear equations

$$ X_0 + 2 X_1 = 1 $$
$$ 3X_0 + 5X_1 = 2 $$

### Non-homo. linear equ.
$$A X = B$$

In [12]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

x = np.linalg.solve(a, b)

print(x)

[-1.  1.]


### Inverse of matrix

In [13]:
a = [[1, 2], 
     [3, 5]]

a_inv = np.linalg.inv(a)

print(a_inv)

[[-5.  2.]
 [ 3. -1.]]


In [14]:
a = np.array([[1, 2, 3],
              [3, 5, 9],
              [7, 1, 4]])

print(a.diagonal())
# or 
print(np.diag(a))
# specific diagonal
print(np.diag(a, k = 1))

[1 5 4]
[1 5 4]
[2 9]


### Transposes a matrix

In [15]:
a = np.array([[1, 2, 3],
              [3, 5, 9],
              [7, 1, 4]])

np.transpose(a)

array([[1, 3, 7],
       [2, 5, 1],
       [3, 9, 4]])

### For [more](https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/intro.html)