In [1]:
import numpy as np

In [2]:
import math
a = np.sin(30)
b = np.sin(30 * np.pi / 180)
# or use math.radians() from math library
c = np.sin(math.radians(30))
# or use deg2rad() from numpy library
d = np.sin(np.deg2rad(30))

print(a)
print(b)
print(c)
print(d)

-0.9880316240928618
0.49999999999999994
0.49999999999999994
0.49999999999999994


In [3]:
a = np.round(4.609661)
b = np.round(4.619661, 2)  # look at 3rd digit (9) 
c = np.round(4.619061, 4)  # look at 5th digit (6) greater than 4
d = np.round(4.619041, 4)  # look at 5th digit (4) less than 5

print(a)
print(b)
print(c)
print(d)

5.0
4.62
4.6191
4.619


In [4]:
a = np.floor(4.609661)
b = np.ceil (4.619661)

print(a)
print(b) 

4.0
5.0


In [5]:
a = np.mod(10, 3)
b = np.mod(10, -3)
c = np.mod(-10, 3)
d = np.mod(-10, -3)

print(a)
print(b)
print(c)
print(d)

1
-2
2
-1


In [6]:
a = np.power(2, 3)
b = np.power(-2, 3)

# c = np.power(2, -3)   not allowed
# d = np.power(-2, -3)  not allowed

print(a)
print(b)

8
-8


In [7]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(lst)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(lst)

print(lst)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
multi_lst = [[1, 2], [3, 4], [5, 6]]
a = np.array(multi_lst)

print(multi_lst)
print(a)

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
empty_lst = np.empty((3, 2))
print(empty_lst)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 2.31420855e-306]
 [1.89146896e-307 7.56571288e-307]]


In [11]:
empty_lst = 0 * empty_lst
print(empty_lst)

# or

zeros_lst = np.zeros((3, 2))
print(zeros_lst)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
a = np.random.uniform(1, 20)              # one real number from 1 to 20
b = np.random.uniform(2, 20, 5)           # 5 real numbers from 2 to 20
print(a)
print(b)
sorteda = np.sort(b)
print(sorteda)

16.636717568546455
[19.82876016  6.74081295 10.95592431  2.92721419  2.21569771]
[ 2.21569771  2.92721419  6.74081295 10.95592431 19.82876016]


In [13]:
a = np.random.random((3, 20))              # 3 rows, 20 columns of real numbers

print(a)

[[0.13862423 0.29650473 0.8519964  0.31927586 0.44758083 0.94195145
  0.73757394 0.35106661 0.15168012 0.75012629 0.20809339 0.47129378
  0.65705705 0.46892129 0.61651308 0.19959153 0.90805679 0.92992259
  0.217207   0.144824  ]
 [0.23578698 0.83434764 0.55651436 0.17270336 0.10928834 0.62247273
  0.66764875 0.07437761 0.02229954 0.01473885 0.64494731 0.56433391
  0.57252874 0.82501373 0.02259291 0.22285423 0.97333437 0.28154528
  0.03425036 0.1870049 ]
 [0.10650516 0.40057229 0.66101152 0.45416394 0.93466784 0.28306885
  0.00131382 0.76598397 0.63830072 0.58814339 0.09027962 0.2118218
  0.08729158 0.90352974 0.03061685 0.45940624 0.46373514 0.24685613
  0.43874535 0.63643686]]


In [14]:
a = np.random.normal(0, 1, 10)              # 10 real numbers from 0 to 1
print(a)

sorteda = np.sort(a)
print(sorteda)

[-2.15668865 -1.31343995  0.27696199 -1.11251512 -0.51072842  1.57949881
  1.31677145 -1.15335672 -1.1320502  -1.27940719]
[-2.15668865 -1.31343995 -1.27940719 -1.15335672 -1.1320502  -1.11251512
 -0.51072842  0.27696199  1.31677145  1.57949881]


In [15]:
a = np.random.randint(1, 10, 10)              # 10 integer numbers from 1 to 10
b = np.random.randint(5, size=3)              # 3 integer numbers from 0 to 5
c = np.random.randint(2, 10, size=3)          # 3 integer numbers from 2 to 10 
d = np.random.randint(5, size=(2, 4))         # 2 rows, 4 columns of integer numbers from 0 to 5

print(a)
print(b)
print(c)
print(d)

[6 1 8 4 2 8 5 8 5 9]
[1 1 1]
[2 8 3]
[[2 0 1 0]
 [2 4 4 1]]


In [16]:
a = np.random.randint(1, 10, 25)        # 25 integer numbers from 1 to 10
print(a)

b = np.reshape(a, (5, 5))               # 5 rows, 5 columns
print(b)

# or

a = a.reshape(5, 5)
print(a)

[6 1 9 3 3 8 9 5 6 2 5 3 3 2 7 3 2 6 1 3 9 3 2 8 3]
[[6 1 9 3 3]
 [8 9 5 6 2]
 [5 3 3 2 7]
 [3 2 6 1 3]
 [9 3 2 8 3]]
[[6 1 9 3 3]
 [8 9 5 6 2]
 [5 3 3 2 7]
 [3 2 6 1 3]
 [9 3 2 8 3]]


In [17]:
a = np.random.rand(10)              # 10 real numbers from 0 to 1
b = np.random.randn(10)             # 10 real numbers from -1 to 1
print(a)
print(b)

[0.50454058 0.62796042 0.18423153 0.54022764 0.6472656  0.91942175
 0.88697251 0.40304249 0.29933256 0.44766652]
[-0.96400594 -0.72856323  2.20322473 -0.56021456  0.02165504 -2.20888255
 -0.50781909 -0.98536416 -1.18460461  0.8914907 ]


In [18]:
a = np.random.rand(2, 5)             # 2 rows, 5 columns of real numbers from 0 to 1

print(a)

[[0.88671848 0.37960085 0.40112191 0.22804195 0.86710253]
 [0.52614247 0.35518352 0.34163579 0.01452343 0.28612167]]


In [19]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.random.shuffle(a)

print(a)

[ 4  6  9  8  2 10  1  5  3  7]


In [20]:
a = np.zeros(5)                       # array of 5 zeros
b = np.zeros((2, 3))                  # 2d array (2 rows, 3 columns) of zeros
c = np.zeros((2, 3, 4))               # 3d array (2 rows, 3 columns, 4 layers) of zeros
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [21]:
a = np.ones(5)                        # array of 5 ones
b = np.ones((2, 3))                   # 2d array (2 rows, 3 columns) of ones

print(a)
print(b)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
a = np.eye(5)                         # 5x5 identity matrix
# or
b = np.identity(5)                    # 5x5 identity matrix


c = np.eye(3, 4)                      # 3x4 identity matrix

print(a, end="\n\n")
print(b, end="\n\n")
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [23]:
a = np.diag([1, 2, 3, 4, 5])          # 5x5 diagonal matrix
b = np.diag([1, 2, 3, 4, 5], k=2)     # diagonal start from 2

print(a)
print(b)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[0 0 1 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 4 0]
 [0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [24]:
a = np.full((3, 3), 5)                # 3x3 matrix of 5

print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [25]:
a = np.arange(10)                      # 0 to 9
b = np.arange(1, 10)                   # 1 to 9
c = np.arange(1, 10, 2)                # 1 to 9 with step of 2
d = np.arange(10, 1, -1)               # 10 to 2 with step of -1
e = np.arange(10, 1, -3)               # 10 to 2 with step of -3

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]
[10  7  4]


In [26]:
a = np.arange(10).reshape(2, 5)       # 2 rows, 5 columns of 0 to 9
# b = np.arange(10).reshape(5, 3)     # error (3 * 5 != 10)
c = np.arange(12).reshape(3, 2, 2)    # 3d array (3 rows, 2 columns, 2 layers) of 0 to 11
# d = np.arange(16).reshape(3, 2, 2)  # error (3 * 2 * 2 != 16)

print(a)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [27]:
a = np.linspace(5, 20)             # 50 numbers from 5 to 20 separated by equal spaces
b = np.linspace(5, 20, 10)         # 10 numbers from 5 to 20
c = np.linspace(5, 20, 10, endpoint=False)         # 10 numbers from 5 to 20 without the last number(20) and no or one digit after the point
d = np.linspace(5, 20, 10, endpoint=True)          # 10 numbers from 5 to 20

print(a)
print(b)
print(c)
print(d)

[ 5.          5.30612245  5.6122449   5.91836735  6.2244898   6.53061224
  6.83673469  7.14285714  7.44897959  7.75510204  8.06122449  8.36734694
  8.67346939  8.97959184  9.28571429  9.59183673  9.89795918 10.20408163
 10.51020408 10.81632653 11.12244898 11.42857143 11.73469388 12.04081633
 12.34693878 12.65306122 12.95918367 13.26530612 13.57142857 13.87755102
 14.18367347 14.48979592 14.79591837 15.10204082 15.40816327 15.71428571
 16.02040816 16.32653061 16.63265306 16.93877551 17.24489796 17.55102041
 17.85714286 18.16326531 18.46938776 18.7755102  19.08163265 19.3877551
 19.69387755 20.        ]
[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]
[ 5.   6.5  8.   9.5 11.  12.5 14.  15.5 17.  18.5]
[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


In [28]:
a = np.linspace(0, 50, 12)          # 12 numbers from 0 to 50
b = a.reshape(2, 3, 2)

print(a)
print(b)

# or

c = np.linspace(0, 50, 12).reshape(2, 3, 2)
print()
print(c)

[ 0.          4.54545455  9.09090909 13.63636364 18.18181818 22.72727273
 27.27272727 31.81818182 36.36363636 40.90909091 45.45454545 50.        ]
[[[ 0.          4.54545455]
  [ 9.09090909 13.63636364]
  [18.18181818 22.72727273]]

 [[27.27272727 31.81818182]
  [36.36363636 40.90909091]
  [45.45454545 50.        ]]]

[[[ 0.          4.54545455]
  [ 9.09090909 13.63636364]
  [18.18181818 22.72727273]]

 [[27.27272727 31.81818182]
  [36.36363636 40.90909091]
  [45.45454545 50.        ]]]


In [29]:
a = np.random.randint(-9, 15, (3, 4))
print(a)

greaterThanZero = np.count_nonzero(a)   # count number of elements that are not equal to 0
print(greaterThanZero)

greaterThanfive = np.count_nonzero(a > 5)   # count number of elements that are greater than 5
print(greaterThanfive)

lessThanfive = np.count_nonzero(a < 5)   # count number of elements that are less than 5
print(lessThanfive)


[[-3 -7  4  8]
 [10 -8 13 11]
 [-8  1 -6  6]]
12
5
7


In [30]:
a = np.random.randint(-9, 15, (3, 4))
b = np.count_nonzero(a > 5, axis = 0)   # count number of elements that are greater than 5 in each column
c = np.count_nonzero(a > 5, axis = 1)   # count number of elements that are greater than 5 in each row

print(a)
print(b)
print(c)

[[ 4  5 11 -5]
 [-4  7 -9  0]
 [ 2  9 13  8]]
[0 2 2 1]
[1 1 3]


In [31]:
a = np.random.randint(-9, 15, (3, 4))
b = np.any(a > 5)             # check if any element is greater than 5
c = np.any(a > 5, axis = 0)   # check if any element in the column is greater than 5
d = np.any(a > 5, axis = 1)   # check if any element in the row is greater than 5

print(a)
print(b)
print(c)
print(d)

[[10 -7 -7 -9]
 [ 1  6  2  4]
 [ 8  4 -8 -3]]
True
[ True  True False False]
[ True  True  True]


In [32]:
a = np.random.randint(-9, 15, (3, 4))

b = np.all(a > 5)             # check if all elements are greater than 5
c = np.all(a > 5, axis = 0)   # check if all elements in the column are greater than 5
d = np.all(a > 5, axis = 1)   # check if all elements in the row are greater than 5

print(a)
print(b)
print(c)
print(d)

[[-3  4  0  6]
 [12  6 -7 12]
 [-7  8 10  5]]
False
[False False False False]
[False False False]


In [33]:
a = np.random.randint(-9, 15, (3, 4))
b = a > 5                   # check if elements are greater than 5
c = a < 5                   # check if elements are less than 5
print(a, end="\n\n")

print(b)                    # print true if elements are greater than 5 and false otherwise for each element
print(a[b], end="\n\n")     # print elements that are greater than 5

print(c)                    # print true if elements are less than 5 and false otherwise for each element
print(a[c])                 # print elements that are less than 5

[[-4 11 -1 -4]
 [13  0 -2 -7]
 [-4  1 -6  4]]

[[False  True False False]
 [ True False False False]
 [False False False False]]
[11 13]

[[ True False  True  True]
 [False  True  True  True]
 [ True  True  True  True]]
[-4 -1 -4  0 -2 -7 -4  1 -6  4]


In [34]:
print(a[b & c])              # print elements that are greater than 5 and less than 5 (logicaly its imposible to have less than 5 and greater than 5) but it's useful in ather cases 
print(a[b | c])              # print elements that are greater than 5 or less than 5 (not equal 5)
print(a[~b])                 # print elements that are not greater than 5

[]
[-4 11 -1 -4 13  0 -2 -7 -4  1 -6  4]
[-4 -1 -4  0 -2 -7 -4  1 -6  4]


In [35]:
a = np.arange(12).reshape(3, 4)
print(a, end="\n\n")

b = np.arange(12).reshape(3, 4)

c = 2 * a
print(c, end="\n\n")

d = np.isclose(a, b)
print(d, end="\n\n")

e = np.isclose(a, c)
print(e, end="\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ True False False False]
 [False False False False]
 [False False False False]]



In [36]:
f = np.isclose(a, b, atol=0.1)      # atol = absolute tolerance
print(f, end="\n\n")

g = np.isclose(a, c, atol=0.1)
print(g, end="\n\n")

h = np.isclose(a, b, rtol=0.1)      # rtol = relative tolerance
print(h, end="\n\n")

i = np.isclose(a, c, rtol=0.1)
print(i, end="\n\n")

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ True False False False]
 [False False False False]
 [False False False False]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ True False False False]
 [False False False False]
 [False False False False]]



In [37]:
a = np.arange(10)

b = np.array([0.] * 10)                # create an array of 10 zeros
np.multiply(a, 10, out = b)
print(b, end="\n\n")
# or

b = np.zeros(10)
np.multiply(a, 10, out = b)
print(b, end="\n\n")
# or

b = np.multiply(a, 10.)
print(b, end="\n\n")
# or

b = 10. * a
print(b)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [38]:
x = np.arange(4)
y = np.empty(4)

np.power(x, 2, out = y)

print(x)
print(y)

[0 1 2 3]
[0. 1. 4. 9.]


In [39]:
a = np.arange(1, 10)
b = np.add.reduce(a)             # sum of all elements
c = np.add.accumulate(a)         # cumulative sum of all elements (prefix sum)
d = np.multiply.reduce(a)        # product of all elements
e = np.multiply.accumulate(a)    # cumulative product of all elements (prefix product)

print(a)
print(b)                      
print(c)
print(d)
print(e)

[1 2 3 4 5 6 7 8 9]
45
[ 1  3  6 10 15 21 28 36 45]
362880
[     1      2      6     24    120    720   5040  40320 362880]


In [40]:
a = np.arange(1, 10)
b = np.arange(2, 6)

c = np.multiply.outer(a, b)     # multiply b by each element in a in separate rows

print(a)
print(b)
print(c)

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[[ 2  3  4  5]
 [ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]
 [10 15 20 25]
 [12 18 24 30]
 [14 21 28 35]
 [16 24 32 40]
 [18 27 36 45]]


In [41]:
a = np.arange(1, 10)
b = np.arange(2, 6)

c = np.add.outer(a, b)     # add each element in a to b in separate rows

print(a)
print(b)
print(c)

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[[ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [42]:
a = np.arange(1, 19, 3)
print(len(a))                # length of array in one dimension = size

b = np.arange(1, 19).reshape(2, 9)
print(b)
print(len(b))                # number of rows
print(b.shape)               # shape of array
print(b.size)                # number of elements in array
print(b.ndim)                # number of dimensions
print(b.dtype)               # data type of array
print(b.itemsize)            # size of each element in bytes
print(b.nbytes)              # total number of bytes (size * itemsize)

6
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
2
(2, 9)
18
2
int32
4
72


In [43]:
a = np.arange(9).reshape(3, 3)
b = np.trace(a)
print(a)
print(np.diag(a))             # main diagonal elements
print(b)


a = np.arange(1, 13)
b = a.reshape(3, 4)
print(b)
print(np.diag(b))
c = np.trace(b)              # sum of main diagonal elements
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  6 11]
18


In [44]:
a = np.arange(9).reshape(3, 3)

b = np.linalg.det(a)         # determinant
print(b)

# c = np.linalg.inv(a)         # inverse
# print(c)

d = np.linalg.eig(a)         # eigenvalues
print(d)

0.0
(array([ 1.33484692e+01, -1.34846923e+00, -1.26963291e-15]), array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [45]:
a = np.arange(14)
b, c = np.split(a, [5])             
d, e, f = np.split(a, [5, 8])       # split (with array use []) at 5th element and 8th element
print(b)
print(c)
print(d)
print(e)
print(f)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13]
[0 1 2 3 4]
[5 6 7]
[ 8  9 10 11 12 13]


In [46]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b, c, d = np.split(a, (5, 8))        # split (with list use ()) at 5th and 8th elements

print(b)
print(c)

[1 2 3 4 5]
[6 7 8]


In [47]:
a = np.arange(9).reshape(3, 3)
b = np.arange(12).reshape(4, 3)
c = np.vstack((a, b))               # stack arrays vertically should be same number of columns
# d = np.hstack((a, b))               # error: arrays must have same number of rows
print(a)
print(b)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
a = np.arange(9).reshape(3, 3)
b = np.arange(12).reshape(3, 4)
c = np.hstack((a, b))               # stack arrays horizontally should be same number of rows
# d = np.vstack((a, b))               # error: arrays must have same number of columns

print(a)
print(b)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  0  1  2  3]
 [ 3  4  5  4  5  6  7]
 [ 6  7  8  8  9 10 11]]


In [49]:
a = np.arange(9).reshape(3, 3)
b = np.arange(9).reshape(3, 3)
c = np.concatenate([a, b], axis = 1)               # concatenate (a and b should be 2d or 3d), axis = 0)
print(a)
print(b)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]
